// <auto-generated />
using System;
using MealPreparationService.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MealPreparationService.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260311180423_FixMenuMealRecipeCompositeKey")]
    partial class FixMenuMealRecipeCompositeKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MealPreparationService.Domain.Entities.AIcreditPackage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CreditAmount")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AIcreditPackages", t =>
                        {
                            t.HasCheckConstraint("CK_AIcreditPackage_Price", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.AIcreditTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AIcreditPackageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentGatewayId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AIcreditPackageId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PaymentGatewayId");

                    b.ToTable("AIcreditTransactions");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentCredits")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleAuthId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleAuthId");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Allergy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Cart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.CartItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MenuMealId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("MenuMealId");

                    b.ToTable("CartItems", t =>
                        {
                            t.HasCheckConstraint("CK_CartItem_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.DailyMenu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MenuDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("DailyMenus");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.DeliverySchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverContact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("OrderId");

                    b.ToTable("DeliverySchedules");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Fridge", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Fridges");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.FridgeItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FridgeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("FridgeId");

                    b.HasIndex("IngredientId");

                    b.ToTable("FridgeItems");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.GoogleAuth", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("GoogleAuths");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.HealthProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CalorieGoal")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HealthNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("Height")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("HealthProfiles");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.HealthProfileAllergy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AllergyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HealthProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AllergyId");

                    b.HasIndex("HealthProfileId");

                    b.ToTable("HealthProfileAllergies");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.HealthProfileIngredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HealthProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RelationshipTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HealthProfileId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RelationshipTypeId");

                    b.ToTable("HealthProfileIngredients");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.IngredientAllergy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AllergyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AllergyId");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientAllergies");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.IngredientNutrient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AmountPer100")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NutrientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("NutrientId");

                    b.ToTable("IngredientNutrients");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Meal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CarbsG")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FatG")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("MealFinished")
                        .HasColumnType("bit");

                    b.Property<int>("MealTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ProteinG")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ServerDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCalories")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("PlanId");

                    b.HasIndex("StatusId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.MealPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HealthProfileId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("HealthProfileId");

                    b.HasIndex("StatusId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.MealRecipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MealId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("RecipeId");

                    b.ToTable("MealRecipes");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.MealType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("MealTypes");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.MenuMeal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("CarbsG")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FatG")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MealTypeId")
                        .HasColumnType("int");

                    b.Property<string>("MenuId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProteinG")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCalories")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuMeals", t =>
                        {
                            t.HasCheckConstraint("CK_MenuMeal_AvailableQuantity", "[AvailableQuantity] >= 0");

                            t.HasCheckConstraint("CK_MenuMeal_Price", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.MenuMealRecipe", b =>
                {
                    b.Property<string>("MenuMealId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecipeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MenuMealId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("MenuMealRecipes");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Nutrient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Nutrients");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderConfirmedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentGatewayId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentGatewayId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderConfirmedBy");

                    b.HasIndex("PaymentGatewayId");

                    b.HasIndex("PaymentGatewayId1");

                    b.HasIndex("StatusId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Order_Amount", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MenuMealId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuMealId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails", t =>
                        {
                            t.HasCheckConstraint("CK_OrderDetail_Quantity", "[Quantity] > 0");

                            t.HasCheckConstraint("CK_OrderDetail_UnitPrice", "[UnitPrice] >= 0");
                        });
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.PaymentGateway", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("PaymentGateways");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeIngredient_Amount", "[Amount] > 0");
                        });
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.RelationshipType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("RelationshipTypes");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.RevenueReport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAiCreditRev")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOrderRev")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalOrdersCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSubscriptionRev")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RevenueReports", t =>
                        {
                            t.HasCheckConstraint("CK_RevenueReport_Month", "[Month] >= 1 AND [Month] <= 12");

                            t.HasCheckConstraint("CK_RevenueReport_Year", "[Year] > 0");
                        });
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.SubscriptionPackage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditAmount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPackages", t =>
                        {
                            t.HasCheckConstraint("CK_SubscriptionPackage_DurationDays", "[DurationDays] > 0");

                            t.HasCheckConstraint("CK_SubscriptionPackage_Price", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.SystemConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentGatewayId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionPackageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("PaymentGatewayId");

                    b.HasIndex("SubscriptionPackageId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.AIcreditTransaction", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.AIcreditPackage", "AIcreditPackage")
                        .WithMany("AIcreditTransactions")
                        .HasForeignKey("AIcreditPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Account", "Account")
                        .WithMany("AIcreditTransactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.PaymentGateway", "PaymentGateway")
                        .WithMany("AIcreditTransactions")
                        .HasForeignKey("PaymentGatewayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AIcreditPackage");

                    b.Navigation("Account");

                    b.Navigation("PaymentGateway");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Account", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.GoogleAuth", "GoogleAuth")
                        .WithMany("Accounts")
                        .HasForeignKey("GoogleAuthId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealPreparationService.Domain.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoogleAuth");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Cart", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Account", "Account")
                        .WithMany("Carts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.MenuMeal", "MenuMeal")
                        .WithMany("CartItems")
                        .HasForeignKey("MenuMealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("MenuMeal");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.DailyMenu", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Status", "Status")
                        .WithMany("DailyMenus")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.DeliverySchedule", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Account", "Driver")
                        .WithMany("DeliverySchedules")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Order", "Order")
                        .WithMany("DeliverySchedules")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Fridge", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Account", "Account")
                        .WithMany("Fridges")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.FridgeItem", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Fridge", "Fridge")
                        .WithMany("FridgeItems")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Fridge");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.HealthProfile", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Account", "Account")
                        .WithMany("HealthProfiles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.HealthProfileAllergy", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Allergy", "Allergy")
                        .WithMany("HealthProfileAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.HealthProfile", "HealthProfile")
                        .WithMany("HealthProfileAllergies")
                        .HasForeignKey("HealthProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("HealthProfile");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.HealthProfileIngredient", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.HealthProfile", "HealthProfile")
                        .WithMany("HealthProfileIngredients")
                        .HasForeignKey("HealthProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("HealthProfileIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.RelationshipType", "RelationshipType")
                        .WithMany("HealthProfileIngredients")
                        .HasForeignKey("RelationshipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HealthProfile");

                    b.Navigation("Ingredient");

                    b.Navigation("RelationshipType");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.IngredientAllergy", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Allergy", "Allergy")
                        .WithMany("IngredientAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("IngredientAllergies")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.IngredientNutrient", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("IngredientNutrients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Nutrient", "Nutrient")
                        .WithMany("IngredientNutrients")
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Meal", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.MealType", "MealType")
                        .WithMany("Meals")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.MealPlan", "MealPlan")
                        .WithMany("Meals")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Status", null)
                        .WithMany("Meals")
                        .HasForeignKey("StatusId");

                    b.Navigation("MealPlan");

                    b.Navigation("MealType");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.MealPlan", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Account", "Account")
                        .WithMany("MealPlans")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.HealthProfile", null)
                        .WithMany("MealPlans")
                        .HasForeignKey("HealthProfileId");

                    b.HasOne("MealPreparationService.Domain.Entities.Status", null)
                        .WithMany("MealPlans")
                        .HasForeignKey("StatusId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.MealRecipe", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Meal", "Meal")
                        .WithMany("MealRecipes")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Recipe", "Recipe")
                        .WithMany("MealRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.MenuMeal", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.MealType", "MealType")
                        .WithMany("MenuMeals")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.DailyMenu", "Menu")
                        .WithMany("MenuMeals")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealType");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.MenuMealRecipe", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.MenuMeal", "MenuMeal")
                        .WithMany("MenuMealRecipes")
                        .HasForeignKey("MenuMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Recipe", "Recipe")
                        .WithMany("MenuMealRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuMeal");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Order", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Account", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Account", "ConfirmedByAccount")
                        .WithMany()
                        .HasForeignKey("OrderConfirmedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealPreparationService.Domain.Entities.PaymentGateway", "PaymentGateway")
                        .WithMany()
                        .HasForeignKey("PaymentGatewayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MealPreparationService.Domain.Entities.PaymentGateway", null)
                        .WithMany("Orders")
                        .HasForeignKey("PaymentGatewayId1");

                    b.HasOne("MealPreparationService.Domain.Entities.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfirmedByAccount");

                    b.Navigation("Customer");

                    b.Navigation("PaymentGateway");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.MenuMeal", "MenuMeal")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MenuMealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuMeal");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.PaymentGateway", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Status", "Status")
                        .WithMany("PaymentGateways")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("MealPreparationService.Domain.Entities.Account", "Account")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.PaymentGateway", "PaymentGateway")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PaymentGatewayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPreparationService.Domain.Entities.SubscriptionPackage", "SubscriptionPackage")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("PaymentGateway");

                    b.Navigation("SubscriptionPackage");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.AIcreditPackage", b =>
                {
                    b.Navigation("AIcreditTransactions");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Account", b =>
                {
                    b.Navigation("AIcreditTransactions");

                    b.Navigation("Carts");

                    b.Navigation("DeliverySchedules");

                    b.Navigation("Fridges");

                    b.Navigation("HealthProfiles");

                    b.Navigation("MealPlans");

                    b.Navigation("Orders");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Allergy", b =>
                {
                    b.Navigation("HealthProfileAllergies");

                    b.Navigation("IngredientAllergies");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.DailyMenu", b =>
                {
                    b.Navigation("MenuMeals");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Fridge", b =>
                {
                    b.Navigation("FridgeItems");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.GoogleAuth", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.HealthProfile", b =>
                {
                    b.Navigation("HealthProfileAllergies");

                    b.Navigation("HealthProfileIngredients");

                    b.Navigation("MealPlans");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("HealthProfileIngredients");

                    b.Navigation("IngredientAllergies");

                    b.Navigation("IngredientNutrients");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Meal", b =>
                {
                    b.Navigation("MealRecipes");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.MealPlan", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.MealType", b =>
                {
                    b.Navigation("Meals");

                    b.Navigation("MenuMeals");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.MenuMeal", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("MenuMealRecipes");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Nutrient", b =>
                {
                    b.Navigation("IngredientNutrients");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Order", b =>
                {
                    b.Navigation("DeliverySchedules");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.PaymentGateway", b =>
                {
                    b.Navigation("AIcreditTransactions");

                    b.Navigation("Orders");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("MealRecipes");

                    b.Navigation("MenuMealRecipes");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.RelationshipType", b =>
                {
                    b.Navigation("HealthProfileIngredients");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.Status", b =>
                {
                    b.Navigation("DailyMenus");

                    b.Navigation("MealPlans");

                    b.Navigation("Meals");

                    b.Navigation("Orders");

                    b.Navigation("PaymentGateways");
                });

            modelBuilder.Entity("MealPreparationService.Domain.Entities.SubscriptionPackage", b =>
                {
                    b.Navigation("UserSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
